name: Bot Prosperidad Divina - Ejecución Aleatoria

on:
  schedule:
    - cron: '1 6 * * *'
    - cron: '13 7 * * *'
    - cron: '58 8 * * *'
    - cron: '46 9 * * *'
    - cron: '39 10 * * *'
    - cron: '15 11 * * *'
    - cron: '2 12 * * *'
    - cron: '37 13 * * *'
    - cron: '34 14 * * *'
    - cron: '52 15 * * *'
    - cron: '17 16 * * *'
    - cron: '45 17 * * *'
    - cron: '35 18 * * *'
    - cron: '31 19 * * *'
    - cron: '18 20 * * *'
    - cron: '7 21 * * *'
    - cron: '38 22 * * *'
    - cron: '19 23 * * *'
    - cron: '40 0 * * *'
    - cron: '56 1 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  ejecutar-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install google-generativeai google-auth google-auth-oauthlib google-api-python-client python-dateutil
        
    - name: Ejecutar Bot (5 comentarios exactos)
      env:
        GEMINI_API_KEY: AIzaSyAet7CWrWUtBdq5dX8GMcyuvfRaSZQ389g
        YOUTUBE_CREDENTIALS_COMMENTS: {
  "token": "ya29.a0AS3H6NxiefT8FdjjF2fECy6PZdGUghGXqPD8WOwbbNiVRfMeCq1Bs_MAQXG4d5G-OPRhs6iyQrgbWQrz1JGsauxUrW6Y-945DCFmJ08m9XAyqizZBi-tUbkaQHK0c_N4-GMgxw60FXG_JhlW7Bontopuz4tQgnnqBXPC5X1vXA_A60HsWrub3eBSt9Eva2rVBrKEil4aCgYKAcASARISFQHGX2MidHrae49U7tcaUf7SH6wipw0206",
  "refresh_token": "1//01viCn-DvUDhZCgYIARAAGAESNwF-L9IrW7kiSEGa91C7zpZ3sreMizmxmnm3_fVcy02L2PJ_3TvA0mhDwe30N1sgo_j_nhoPZw0",
  "token_uri": "https://oauth2.googleapis.com/token",
  "client_id": "370965148704-2uvfjhi8quhrohgle4cfprsjqkcjm2g1.apps.googleusercontent.com",
  "client_secret": "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",
  "scopes": [
    "https://www.googleapis.com/auth/youtube.force-ssl"
  ]
}
      run: |
        echo "Ejecutando bot: 5 comentarios exactos"
        echo "Horario aleatorio: $(date +'%H:%M')"
        python bot_prosperidad_divina.py
        
    - name: Guardar cambios
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Bot 6000pts"
        git add .
        if ! git diff --staged --quiet; then
          git commit -m "6000pts - $(date +'%d/%m %H:%M') - 5 comentarios"
          git push origin main || git push --force-with-lease origin main
        fi
